name: Windows-RDP-Australia-Tailscale

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Tailscale Download aur Install Karna
      run: |
        Invoke-WebRequest -Uri https://tailscale.com -OutFile tailscale-setup.exe
        Start-Process -FilePath .\tailscale-setup.exe -ArgumentList "/qn" -Wait
        
    - name: Windows RDP Access Enable Karna
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
    - name: RDP Password Set Karna
      run: |
        net user runneradmin Password@123
        
    - name: Tailscale Connection Connect Karna
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --accept-routes
        
    - name: Loop Chalaye Rakhna
      run: |
        $Loop = 1
        while ($Loop -eq 1) {
          Start-Sleep -Seconds 60
        }
