name: Windows-RDP-Australia-Final

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Windows RDP Access Enable Karna
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
    - name: RDP Password Set Karna
      run: |
        net user runneradmin Password@123
        
    - name: Direct Ping aur Network Activation
      run: |
        Write-Host "Setting up alternate secure proxy..."
        
    - name: Choco Se Loophole Setup
      run: |
        choco install tmate -y
        
    - name: Australia Alternate Tunnel Start Karna
      run: |
        Start-Process tmate -ArgumentList "-F"
        Start-Sleep -Seconds 15
        
    - name: Loop Chalaye Rakhna
      run: |
        $Loop = 1
        while ($Loop -eq 1) {
          Start-Sleep -Seconds 60
        }
